# Generated by Django 5.1.2 on 2024-11-28 22:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='loan_payment',
        ),
        migrations.AddField(
            model_name='loan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loan',
            name='loan_status',
            field=models.CharField(choices=[('APPROVED', 'Aprobado'), ('REJECTED', 'Rechazado'), ('PENDING', 'Pendiente')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='loan',
            name='loan_type',
            field=models.CharField(choices=[('BLACK', 'Black'), ('GOLD', 'Gold'), ('CLASSIC', 'Classic')], default='CLASSIC', max_length=20),
        ),
    ]
