# Generated by Django 5.1.2 on 2024-11-24 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('address_id', models.AutoField(primary_key=True, serialize=False)),
                ('address_name', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'Address',
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('branch_id', models.AutoField(primary_key=True, serialize=False)),
                ('branch_name', models.CharField(max_length=50)),
                ('branch_address', models.CharField(max_length=255)),
                ('fk_branch_address', models.ForeignKey(db_column='fk_branch_address_id', on_delete=django.db.models.deletion.CASCADE, to='sucursales.address')),
            ],
            options={
                'db_table': 'Branch',
            },
        ),
    ]
