# Generated by Django 5.1.2 on 2024-11-24 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sucursales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientType',
            fields=[
                ('client_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('client_type_name', models.CharField(max_length=50)),
                ('client_type_card_amount', models.IntegerField()),
                ('client_type_withdraw_limit', models.IntegerField()),
                ('client_type_fee', models.FloatField()),
            ],
            options={
                'db_table': 'ClientType',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_DNI', models.CharField(max_length=10)),
                ('customer_name', models.CharField(max_length=50)),
                ('customer_surname', models.CharField(max_length=50)),
                ('customer_birth', models.DateField()),
                ('fk_customer_address', models.ForeignKey(db_column='fk_customer_address_id', on_delete=django.db.models.deletion.CASCADE, to='sucursales.address')),
                ('fk_customer_branch', models.ForeignKey(db_column='fk_customer_branch_id', on_delete=django.db.models.deletion.CASCADE, to='sucursales.branch')),
                ('fk_customer_client_type', models.ForeignKey(db_column='fk_customer_client_type_id', on_delete=django.db.models.deletion.CASCADE, to='clientes.clienttype')),
            ],
            options={
                'db_table': 'Customer',
            },
        ),
    ]
