# Generated by Django 5.1.2 on 2024-11-24 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('account_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('account_type_name', models.CharField(max_length=50)),
                ('account_type_currency', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'AccountType',
            },
        ),
        migrations.CreateModel(
            name='CustomerAccount',
            fields=[
                ('customer_account_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_account_balance', models.IntegerField()),
                ('fk_customer_account_account_type', models.ForeignKey(db_column='fk_customer_account_account_type_id', on_delete=django.db.models.deletion.CASCADE, to='cuentas.accounttype')),
                ('fk_customer_account_customer', models.ForeignKey(db_column='fk_customer_account_customer_id', on_delete=django.db.models.deletion.CASCADE, to='clientes.customer')),
            ],
            options={
                'db_table': 'CustomerAccount',
            },
        ),
    ]
