# Generated by Django 5.1.2 on 2024-11-25 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_customer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='fk_customer_address',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='fk_customer_branch',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='fk_customer_client_type',
        ),
    ]
