# Generated by Django 5.1.2 on 2024-11-30 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('account_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('account_type_name', models.CharField(max_length=50)),
                ('account_type_currency', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'AccountType',
            },
        ),
        migrations.CreateModel(
            name='CardBrand',
            fields=[
                ('card_brand_id', models.AutoField(primary_key=True, serialize=False)),
                ('card_brand_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'CardBrand',
            },
        ),
        migrations.CreateModel(
            name='ClientType',
            fields=[
                ('client_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('client_type_name', models.CharField(max_length=50)),
                ('client_type_card_amount', models.IntegerField()),
                ('client_type_withdraw_limit', models.IntegerField()),
                ('client_type_fee', models.FloatField()),
            ],
            options={
                'db_table': 'ClientType',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_DNI', models.CharField(max_length=10)),
                ('customer_name', models.CharField(max_length=50)),
                ('customer_surname', models.CharField(max_length=50)),
                ('customer_birth', models.DateField()),
            ],
            options={
                'db_table': 'Customer',
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('card_id', models.AutoField(primary_key=True, serialize=False)),
                ('card_number', models.CharField(max_length=20)),
                ('card_cvv', models.IntegerField()),
                ('card_grand_date', models.DateField(blank=True, null=True)),
                ('card_expire_date', models.DateField(blank=True, null=True)),
                ('card_type', models.CharField(blank=True, max_length=25, null=True)),
                ('fk_card_brand', models.ForeignKey(db_column='fk_card_brand_id', on_delete=django.db.models.deletion.CASCADE, to='Cliente.cardbrand')),
                ('fk_card_customer', models.ForeignKey(db_column='fk_card_customer_id', on_delete=django.db.models.deletion.CASCADE, to='Cliente.customer')),
            ],
            options={
                'db_table': 'Card',
            },
        ),
        migrations.CreateModel(
            name='CustomerAccount',
            fields=[
                ('customer_account_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_account_balance', models.IntegerField()),
                ('fk_customer_account_account_type', models.ForeignKey(db_column='fk_customer_account_account_type_id', on_delete=django.db.models.deletion.CASCADE, to='Cliente.accounttype')),
                ('fk_customer_account_customer', models.ForeignKey(db_column='fk_customer_account_customer_id', on_delete=django.db.models.deletion.CASCADE, to='Cliente.customer')),
            ],
            options={
                'db_table': 'CustomerAccount',
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('loan_id', models.AutoField(primary_key=True, serialize=False)),
                ('loan_payment', models.CharField(max_length=50)),
                ('loan_date', models.DateField()),
                ('loan_total', models.IntegerField()),
                ('fk_loan_customer', models.ForeignKey(db_column='fk_loan_customer_id', on_delete=django.db.models.deletion.CASCADE, to='Cliente.customer')),
            ],
            options={
                'db_table': 'Loan',
            },
        ),
    ]
