# Generated by Django 5.1.2 on 2024-11-30 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Sucursal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_name', models.CharField(max_length=50)),
                ('employee_surname', models.CharField(max_length=50)),
                ('employee_hire_date', models.DateField()),
                ('employee_DNI', models.CharField(max_length=10)),
                ('fk_employee_address', models.ForeignKey(db_column='fk_employee_address_id', on_delete=django.db.models.deletion.CASCADE, to='Sucursal.address')),
                ('fk_employee_branch', models.ForeignKey(db_column='fk_employee_branch_id', on_delete=django.db.models.deletion.CASCADE, to='Sucursal.branch')),
            ],
            options={
                'db_table': 'Employee',
            },
        ),
    ]
