# Generated by Django 5.1.2 on 2024-11-24 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardBrand',
            fields=[
                ('card_brand_id', models.AutoField(primary_key=True, serialize=False)),
                ('card_brand_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'CardBrand',
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('card_id', models.AutoField(primary_key=True, serialize=False)),
                ('card_number', models.CharField(max_length=20)),
                ('card_cvv', models.IntegerField()),
                ('card_grand_date', models.DateField(blank=True, null=True)),
                ('card_expire_date', models.DateField(blank=True, null=True)),
                ('card_type', models.CharField(blank=True, max_length=25, null=True)),
                ('fk_card_customer', models.ForeignKey(db_column='fk_card_customer_id', on_delete=django.db.models.deletion.CASCADE, to='clientes.customer')),
                ('fk_card_brand', models.ForeignKey(db_column='fk_card_brand_id', on_delete=django.db.models.deletion.CASCADE, to='tarjetas.cardbrand')),
            ],
            options={
                'db_table': 'Card',
            },
        ),
    ]
